### ISSUE TITLE
support passing data on redirects

### ISSUE THREAD

**Issue by rosshadden** [ConnectAi/cs#10]
Basically, make `{{extend}}` work with `req.redirect()`.

> NOTE: I don't actually remember anything about this one right now---I pulled it from our old TODO.

**Comment by optikalefx** [comment]
we don't even have {{extend}} anymore. We have hook and bind

**Comment by rosshadden** [comment]
I don't even remember what extend was... was that how we put scripts and stylesheets (and any arbitrary block for that matter) into the layout, from a specific view?

**Comment by optikalefx** [comment]
yea, the old days. ha
