### ISSUE TITLE
make dynamic layouts easier

### ISSUE THREAD

**Issue by rosshadden** [ConnectAi/cs#14]
Make dynamic layouts (or lack thereof) easier, based on [`req.xhr`](http://expressjs.com/4x/api.html#req.xhr).

**Comment by optikalefx** [comment]
what do you mean? more than sending a new layout to res.view or setting layout in the * method via res.layout?

**Comment by rosshadden** [comment]
At one point we wanted to be able to easily serve something different for AJAX requests than for straight up browser requests.  It's possible as-is, using [`req.xhr`](http://expressjs.com/4x/api.html#req.xhr), but we talked about making it easier in CS so devs don't have to know that you can do it in express.

**Comment by optikalefx** [comment]
I think this is easy enough.
